# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EernDnfmgFl2TbbdfoWi2vSFLthRfU57
"""

pip install pandas

import pandas as pd

my_list = [2, 4, 6, 8]
series_from_list = pd.Series(my_list)
print(series_from_list)

import numpy as np
my_arrary = np.array(my_list)
series_from_array = pd.Series(my_arrary)
print(series_from_array)
#every time you want to work with a new library you have to 'import' them

my_dict = {
    "A" : [10,20,30],
    "B" : [40,50,60],
    "C" : [70,80,90]
}
series_from_dict = pd.Series(my_dict)
print(series_from_dict)

my_list_of_things = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
df_from_list_of_things = pd.DataFrame(my_list_of_things, columns=['Live', 'Freeze', 'Die'])
print(df_from_list_of_things)

pd.read_csv('students.csv')

df = pd.read_csv('students.csv')
df.head()
#HEAD shows you the top of the list

df = pd.read_csv('students.csv')
df.tail()
#TAIL shows you the bottom of the list

print(df.columns)

print(df.dtypes)

print(df.describe())

print(df.describe(include = 'all'))

df['gender'].value_counts()

df.isnull() #not useful, will show another useful way - Professor "print(df.isnull().sum())"

print(df.isnull().sum())

df.dropna(axis=1) #axis = column

df.fillna(df.average())

import pandas as pd

df = pd.read_csv('students.csv')

df['gender'].replace({'female': 'F', 'male': 'M'}, inplace=True)